version: '3'

services:
  mongodb:
    image: mongo
    #    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1231
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017